repos:

- repo: local
  hooks:
    - id: autoflake
      name: autoflake
      entry: autoflake -r -i --remove-all-unused-imports --remove-unused-variables
      language: system
      types: [ python ]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.292
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
