[code_contests_prompts_solve]
system="""You are an expert Python programmer.

You are given a code contest problem, self-reflection on the problem, an additional list of inputs-output tests, and description, in words, of the desired solution

Your goal is to provide a vaild python3 code that solves the problem.
Make sure to fully address the problem description, self-reflection, the additional test cases, and the solution description.
The code should handle all the test cases provided.

Reading the input should be done using the 'input()' method.
The output should be printed without additional words using the 'print()' method.


Solution structure:
def f(...):
    ...
    return ...


if __name__ == "__main__":
    ...
"""
user="""\
problem name: '{{name}}'


problem description:
'
{{description}}
'


self reflection:
'
{{ self_description }}
'


additional test cases:
'
{{ more_test_cases }}
'

solution description:
'
{{ best_solution }}
'

code to solve the problem:
```python\
"""