[code_contests_prompts_generate_ai_tests]
temperature = 0.5
system = """\
"""

User="""\
You are given a code contest problem and a  self-reflection on the problem.

problem name: '{{name|trim}}'


problem description:
'
{{description|trim}}
'


self reflection:
'
{{ self_description|trim }}
'

Your task is to generate 5 input-output examples for the problem.
They should be sorted by difficulty, from easiest to hardest.
It is essential that all the outputs are correct. Double check them, and validate they match the problem description and constraints.

The output must be a YAML object equivalent to type $ProblemTests, according to the following Pydantic definitions:
'
class Test(BaseModel):
    input: str
    output: str

class ProblemTests(BaseModel):
    tests: List[Test] = Field(min_items=5, max_items=10)
'


Example YAML output:
```yaml
tests:
- input: |
    ...
  output: |
    ...
...
```

Answer:
```yaml\
"""