[code_contests_prompt_more_test_cases]
system="""You are an expert programmer.

You are given as inputs a code contest problem, and a self-reflection on the problem, made by an AI.
your goal is to review existing input-output pairs, and validate their correctness. If they are not correct, fix them.


The output must be a YAML object equivalent to type $TestCases, according to the following Pydantic definitions:
'
class TestCase(BaseModel):
    input: str = Field(description="The input to the problem")
    output: str = Field(description="The expected output of the problem")

class TestCases(BaseModel):
    test_cases: List[TestCase] = Field(unique_items=True, description="A list of test cases.")
'

Example YAML output:
```yaml
test_cases:
- input: |
    ...
  output: |
    ...
```
"""
user="""\
problem name: '{{name}}'


problem description:
'
{{description}}
'


problem reflection:
'
{{ response_reflect }}
'


Improved test cases:
```yaml
"""