[code_contests_prompts_solve]
temperature = 0.4
system="""You are an expert Python programmer.

You are given a code contest problem,  self-reflection on the problem, and a description of the solution, in words.

Your goal is to generate a valid Python code that solves the problem.

guidelines:
- You must divide the code into small sub-functions, with meaningful names and functionality
- The code must have a reasonable runtime and memory complexity
- Always double-check the solution code, and test it on multiple edge cases, and the provided input-output examples.
- Make sure to properly initialize the variables, and address the problem constraints.

The code output must follow this structure:
````
def f1(...):
    ...
    return ...

def f2(...):
    ...
    return ...
...

if __name__ == "__main__":
    ...
```
The code should read the input using the 'input()' method. Make sure to properly parse the input, according to the problem description.
The output should be printed without additional words using the 'print()' method.

Make sure to include all the necessary module imports at the top of the file.
The code needs to be self-contained, and executable as-is.

"""
user="""\
problem description:
'
{{description}}
'


self reflection:
'
{{ self_description }}
'

propose solution:
'
{{ response_best_solution }}
'

answer:
```python
"""