[config]
model="gpt-4"
#model = "gpt-3.5-turbo-16k"
requests_per_minute=60
fallback_models =[]
#fallback_models=["gpt-3.5-turbo-16k"]
git_provider="github"
publish_output=true
publish_output_progress=true
verbosity_level=0 # 0,1,2
use_extra_bad_extensions=false
use_repo_settings_file=true
ai_timeout=180
max_description_tokens = 500
max_commits_tokens = 500
secret_provider="google_cloud_storage"
cli_mode=false

[solve]
use_baseline = false
do_recording = true
use_recording = false
load_final_code_solution = false

[etl]
private_dataset_cache_dir="~/.cache/huggingface/datasets/alpha_codium"
#private_dataset_cache_dir='/Users/talrid/Desktop/code_contest_dataset'

[code_tester]
tester_type="local" # local, code_contests
sandbox=false
calc_trace=false
use_trace=false
max_trace_lines=50
trace_depth=4
delta=0.0001
prefer_dynamic_programming=true
