[config]
model="gpt-4"
#model = "gpt-3.5-turbo-16k"
requests_per_minute=60
fallback_models =[]
git_provider="github"
verbosity_level=0 # 0,1,2
ai_timeout=180

[dataset]
evaluate_prev_solutions=true


[solve]
# 165 problems
max_iterations = 3 # X iterations to try to solve the problem
reduce_verbose = false
use_baseline = false
do_recording = true
use_recording = false

[self_reflect]
randomize_best_solution = false
prefer_dynamic_programming=false


[public_tests]
max_allowed_calls=6
max_counter_public_tests=2
disable_recording_public_tests=true

[ai_tests]
number_of_ai_tests=8
max_allowed_calls=5

[etl]
private_dataset_cache_dir="~/.cache/huggingface/datasets/alpha_codium"
#private_dataset_cache_dir='/Users/talrid/Desktop/code_contest_dataset'

[code_tester]
tester_type="local" # local, code_contests
order_matters=true
sandbox=false
calc_trace=false
use_trace=false
max_trace_lines=50
trace_depth=4
delta=0.0001
#prefer_dynamic_programming=true


[code_contests_tester]
num_threads = 4
stop_on_first_failure = false
timeout = 10
path_to_python_bin = "/usr/bin/python3.9"
path_to_python_lib = ["/usr/lib", "/usr/lib/python3.9"]
