[config]
#model="gpt-4"
model = "gpt-3.5-turbo-16k"
requests_per_minute=60
fallback_models =[]
git_provider="github"
verbosity_level=0 # 0,1,2
ai_timeout=180

[solve]
use_baseline = false
do_recording = true
use_recording = false
load_final_code_solution = false
number_of_ai_tests=6
revert_to_last_solution_on_failure=true
disable_recording_public_tests=false
max_counter_public_tests=3


[etl]
private_dataset_cache_dir="~/.cache/huggingface/datasets/alpha_codium"
#private_dataset_cache_dir='/Users/talrid/Desktop/code_contest_dataset'

[code_tester]
tester_type="local" # local, code_contests
sandbox=false
calc_trace=false
use_trace=false
max_trace_lines=50
trace_depth=4
delta=0.0001
#prefer_dynamic_programming=true
